Update China holidays: add observed and substituted holidays in 2001-2024
vacanza/python-holidays pull request #1613
Opened 2023-12-30 13:16 UTC by KJhellico

## Proposed change

Update China holidays: add observed and substituted holidays in 2001-2024.

## Type of change

- [ ] New country/market holidays support (thank you!)
- [x] Supported country/market holidays update (calendar discrepancy fix, localization)
- [ ] Existing code/documentation/test/process quality improvement (best practice, cleanup, refactoring, optimization)
- [ ] Dependency update (version deprecation/upgrade)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (a code change causing existing functionality to break)
- [ ] New feature (new python-holidays functionality in general)

## Checklist

- [x] I've followed the [contributing guidelines][contributing-guidelines]
- [x] I've run `make pre-commit`, it didn't generate any changes
- [x] I've run `make test`, all tests passed locally

[contributing-guidelines]: https://github.com/vacanza/python-holidays/blob/beta/CONTRIBUTING.rst
[docs]: https://github.com/vacanza/python-holidays/tree/beta/docs/source

2023-12-30 14:34 UTC, PPsyrius requested changes
Thanks for improving the Chinese calendar, here are some of the Thai language translations that likely need to be changed here. 👀

2023-12-30 14:34 UTC, PPsyrius commented on holidays/locale/th/LC_MESSAGES/CN.po
> +msgstr "วันพัก (แทนที่จาก %s)"
Consider changing this to "วันหยุด (แทน %s)" instead

2023-12-30 14:34 UTC, PPsyrius commented on holidays/locale/th/LC_MESSAGES/CN.po
> +"ครบรอบ 70 "
[The official Thai translation](https://oldweb.ditp.go.th/contents_attach/132578/132578.pdf) uses "ครบรอบ 70 ปีแห่งการได้รับชัยชนะจากสงครามต่อต้านญี่ปุ่นและลัทธิฟาสซิสต์โลก" here so we might want to go with that instead.

(they got some typo in the referenced translation above for the Thai translation of "Fascism" - corrected to [Royal Society of Thailand](https://dictionary.orst.go.th/)'s official spelling)

2023-12-30 15:53 UTC, KJhellico commented
@PPsyrius, thank you! It's Google Translate 🤷🏻‍♂️

2024-01-02 16:54 UTC, arkid15r reviewed
LGTM

2024-01-02 16:54 UTC, arkid15r commented on holidays/countries/china.py
> +            (JAN, 29, JAN, 20),  # spring_festival
The comments look a bit unusual, could you make them look like "Labor day" or "Spring festival" for example?

2024-01-02 16:55 UTC, arkid15r reviewed
BTW, does this PR close https://github.com/vacanza/python-holidays/issues/1601 ?

2024-01-02 23:29 UTC, arkid15r approved these changes

2024-01-02 23:29 UTC, merged