postponed days for Russian holidays in 2024
vacanza/python-holidays pull request #1760
Opened 2024-04-12 16:13 UTC by summicron502

## Proposed change
Added postponed days for Russian holidays in 2024

Added days and translations

## Type of change

- [ ] New country/market holidays support (thank you!)
- [x] Supported country/market holidays update (calendar discrepancy fix, localization)
- [ ] Existing code/documentation/test/process quality improvement (best practice, cleanup, refactoring, optimization)
- [ ] Dependency update (version deprecation/upgrade)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (a code change causing existing functionality to break)
- [ ] New feature (new python-holidays functionality in general)

## Checklist

- [x] I've followed the [contributing guidelines][contributing-guidelines]
- [x] I've run `make pre-commit`, it didn't generate any changes
- [x] I've run `make test`, all tests passed locally

[contributing-guidelines]: https://github.com/vacanza/python-holidays/blob/dev/CONTRIBUTING.rst
[docs]: https://github.com/vacanza/python-holidays/tree/dev/docs/source

2024-04-17 03:38 UTC, PPsyrius requested changes
Thank you for your contribution, although you might want to consider switching to the dedicated substituted holidays pattern instead, as shown in #1613 . :+1:

That and some additional test cases for these postponed holidays would make this PR perfect for merging.

2024-04-17 03:38 UTC, PPsyrius commented on holidays/countries/russia.py
> +from holidays.calendars.gregorian import JAN, FEB, APR, MAY, DEC
```suggestion
from holidays.calendars.gregorian import JAN, FEB, APR, MAY, JUN, DEC
```

2024-04-17 03:38 UTC, PPsyrius commented on holidays/countries/russia.py
> +            (DEC, 31, tr("Перенос 07.01.2024")),
```suggestion
            (APR, 29, APR, 27),
            (APR, 30, FEB, 11),
            (MAY, 10, JUN, 1),
            (DEC, 30, DEC, 28),
            (DEC, 31, JAN, 7),
```

2024-04-17 03:38 UTC, PPsyrius commented on holidays/locale/ru/LC_MESSAGES/RU.po
> +msgstr ""
```suggestion
msgid "%d.%m.%Y"
msgstr ""

msgid "Перенос %s"
msgstr ""
```

2024-04-17 03:38 UTC, PPsyrius commented on holidays/locale/en_US/LC_MESSAGES/RU.po
> +msgstr "Postpone of 07.01.2024"
```suggestion
msgid "%d.%m.%Y"
msgstr "%m/%d/%Y"

msgid "Перенос %s"
msgstr "Postpone of %s"
```

2024-04-17 03:45 UTC, PPsyrius commented on holidays/countries/russia.py
> +        # src: https://www.consultant.ru/document/cons_doc_LAW_455140/
```suggestion
        # src: https://www.consultant.ru/document/cons_doc_LAW_455140/

        # Date format (see strftime() Format Codes).
        substituted_date_format = tr("%d.%m.%Y")
        # Postpone of %s.
        substituted_label = tr("Перенос %s")
```

2024-04-17 03:49 UTC, PPsyrius commented on holidays/countries/russia.py
> +            (DEC, 31, tr("Перенос 07.01.2024")),
Make sure to include the following section below Line 115, too (after the `class RussiaStaticHolidays:` line)

```python3
        # Date format (see strftime() Format Codes).
        substituted_date_format = tr("%d.%m.%Y")
        # Postpone of %s.
        substituted_label = tr("Перенос %s")
```

2024-04-17 08:35 UTC, summicron502 commented
Changes accepted

2024-04-18 03:42 UTC, PPsyrius commented on holidays/locale/ru/LC_MESSAGES/RU.po
> +msgstr ""
```suggestion
#. Date format (see strftime() Format Codes).
msgid "%d.%m.%Y"
msgstr ""

#. Postpone of %s.
#, c-format
msgid "Перенос %s"
msgstr ""
```

2024-04-18 03:44 UTC, PPsyrius commented on holidays/locale/en_US/LC_MESSAGES/RU.po
> +msgstr "Postpone of %s"
```suggestion
#. Date format (see strftime() Format Codes).
msgid "%d.%m.%Y"
msgstr "%m/%d/%Y"

#. Postpone of %s.
#, c-format
msgid "Перенос %s"
msgstr "Postpone of %s"
```

2024-04-18 03:45 UTC, PPsyrius commented on holidays/locale/ru/LC_MESSAGES/RU.po
> +"Project-Id-Version: Python Holidays 0.47\n"
```suggestion
"Project-Id-Version: Python Holidays 0.48\n"
```

2024-04-18 03:45 UTC, PPsyrius commented on holidays/locale/en_US/LC_MESSAGES/RU.po
> +"Project-Id-Version: Python Holidays 0.47\n"
```suggestion
"Project-Id-Version: Python Holidays 0.48\n"
```

2024-04-18 03:54 UTC, PPsyrius requested changes
@summicron502 Other changes (I've put them as subcomments so they may have been overlooked before):

`holidays/countries/russia.py` Line 115-137 (`class RussiaStaticHolidays` section)
```python
class RussiaStaticHolidays:
    # Date format (see strftime() Format Codes).
    substituted_date_format = tr("%d.%m.%Y")
    # Postpone of %s.
    substituted_label = tr("Перенос %s")

    special_public_holidays = {
        # Postponed Days 2023
        # src: https://www.consultant.ru/document/cons_doc_LAW_425407/
        2023: (
            (FEB, 24, JAN, 1),
            (MAY, 8, JAN, 8),
        ),
        # Postponed Days 2024
        # src: https://www.consultant.ru/document/cons_doc_LAW_455140/
        2024: (
            (APR, 29, APR, 27),
            (APR, 30, FEB, 11),
            (MAY, 10, JUN, 1),
            (DEC, 30, DEC, 28),
            (DEC, 31, JAN, 7),
        ),
    }
```
`tests\countries\test_russia.py` Line 30-40 (`def test_special_holidays(self)` section)
```python
    def test_special_holidays(self):
        self.assertHoliday(
            # Postponed Holidays.
            "2023-02-24",
            "2023-05-08",
            "2024-04-29",
            "2024-04-30",
            "2024-05-10",
            "2024-12-30",
            "2024-12-31",
        )
```

2024-04-23 02:07 UTC, arkid15r commented
It's just a friendly reminder to address the CI/CD issues before we could merge this PR.

Thank you!

2024-04-23 09:43 UTC, PPsyrius commented
> @summicron502 Other changes (I've put them as subcomments so they may have been overlooked before):
> 
> `holidays/countries/russia.py` Line 115-137 (`class RussiaStaticHolidays` section)
> 
> ```python
> class RussiaStaticHolidays:
>     # Date format (see strftime() Format Codes).
>     substituted_date_format = tr("%d.%m.%Y")
>     # Postpone of %s.
>     substituted_label = tr("Перенос %s")
> 
>     special_public_holidays = {
>         # Postponed Days 2023
>         # src: https://www.consultant.ru/document/cons_doc_LAW_425407/
>         2023: (
>             (FEB, 24, JAN, 1),
>             (MAY, 8, JAN, 8),
>         ),
>         # Postponed Days 2024
>         # src: https://www.consultant.ru/document/cons_doc_LAW_455140/
>         2024: (
>             (APR, 29, APR, 27),
>             (APR, 30, FEB, 11),
>             (MAY, 10, JUN, 1),
>             (DEC, 30, DEC, 28),
>             (DEC, 31, JAN, 7),
>         ),
>     }
> ```
> 
> `tests/countries/test_russia.py` Line 30-40 (`def test_special_holidays(self)` section)
> 
> ```python
>     def test_special_holidays(self):
>         self.assertHoliday(
>             # Postponed Holidays.
>             "2023-02-24",
>             "2023-05-08",
>             "2024-04-29",
>             "2024-04-30",
>             "2024-05-10",
>             "2024-12-30",
>             "2024-12-31",
>         )
> ```

Please make sure to include this part manually since GitHub doesn't allow code reviewer to suggest sections where the original PR contributor doesn't touch.

2024-04-23 16:13 UTC, arkid15r reviewed
Please find my comments to address below:

2024-04-23 16:13 UTC, arkid15r commented on holidays/locale/en_US/LC_MESSAGES/RU.po
> +msgstr "Postpone of %s"
We normally use  `Выходной (перенесено с %s)` `Day off (substituted from %s)` for the labels

2024-04-23 16:14 UTC, arkid15r commented
> For some reason l10n started to fail
> 
> > from lingva.extract import main as create_pot_file
> > ModuleNotFoundError: No module named 'lingva'
> 
> Is it known problem or that's my fault?

try running `make setup` or `pip install -U lingva`

2024-05-09 16:04 UTC, arkid15r commented
@summicron502 did you have a chance to work on addressing the issues/comments?

2024-05-23 16:36 UTC, closed without merging